version: "3.4"
services:
# Unified frontend
  organizr:
    #image: organizrtools/organizr-v2:latest # deprecated
    image: organizr/organizr
    container_name: organizr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/organizr:/config
    ports:
      - "80:80"
    
# media server
  emby:
    image: linuxserver/emby
    container_name: embyserver
    restart: unless-stopped
    network_mode: host
    volumes:
     - ${CONFIG}/embyserver:/config
     - ${MEDIA}:/mnt/share1
    devices:
     - "/dev/dri:/dev/dri"
    environment:
     - TZ=${TZ}
     - PUID=${PUID}
     - PGID=${PGID}
    
# better container manager
  portainer:
    image: portainer/portainer
    hostname: portainer
    container_name: portainer
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG}/portainer:/data
    environment:
      - TZ=${TZ}

# Torrent Client
# WEBUI ON PORT 8112
  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: host
    #network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${MEDIA}/downloads:/downloads # downloads folder
      - ${CONFIG}/deluge:/config # config files

# API to torrent indices
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    # PORT 9117
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA}/downloads/torrent_drop:/downloads # place where to put .torrent files for manual download
      - ${CONFIG}/jackett:/config # config files
    ports:
      - "9117:9117"

# TV Downloads
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/sonarr:/config # config files
      - ${MEDIA}/tv:/tv # tv shows folder
      - ${MEDIA}/downloads:/downloads # download folder
    ports:
      - "8989:8989"

# Movies downloads
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/radarr:/config # config files
      - ${MEDIA}/movies:/movies # movies folder
      - ${MEDIA}/downloads:/downloads # download folder
    ports:
      - "7878:7878"

# Music Downloads
  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    volumes:
      - ${CONFIG}/lidarr:/config
      - ${MEDIA}/music:/music
      - ${MEDIA}/downloads:/downloads
    ports:
      - "8686:8686"
    
    
# Subtitles downloads
#  bazarr:
#    container_name: bazarr
#    image: linuxserver/bazarr
#    restart: unless-stopped
#    #network_mode: host
#    environment:
#      - PUID=${PUID} # default user id, defined in .env
#      - PGID=${PGID} # default group id, defined in .env
#      - TZ=${TZ} # timezone, defined in .env
#      - UMASK_SET=022 #optional
#    volumes:
#      - ${CONFIG}/bazarr:/config # config files
#      - ${MEDIA}/movies:/movies # movies folder
#      - ${MEDIA}/tv:/tv # tv shows folder
#    ports:
#      - "6767:6767"

# Service availability/status
#   monitorr:
#     container_name: monitorr
#     image: monitorr/monitorr
#     restart: unless-stopped
#     environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#     volumes:
#      - ${CONFIG}/monitorr:/app
#     ports:
#      - "8585:80" 
      